version: '3'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: soturno
      MONGO_INITDB_ROOT_PASSWORD: soturno
    ports:
      - "27017:27017"
    volumes:
      - /home/Docker/Volumes/MongoDB:/data/db